version: "3.7"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "danilo"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "todolist"
    ports:
      - "3308:3306"
    network_mode: "bridge"